language: objective-c
before_install:
  - gem install cocoapods --no-ri --no-rdoc
before_script:
  - export LANG=en_US.UTF-8
  - brew update
  - brew uninstall xctool
  - brew install xctool
xcode_workspace: Example/Artsy+UILabels.xcworkspace
xcode_scheme: LabelsApp
xcode_sdk: iphonesimulator
podfile: Example/Podfile
